// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpqxbqahvwwicukuidph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwcXhicWFodnd3aWN1a3VpZHBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3NTE3ODIsImV4cCI6MjA3OTMyNzc4Mn0.sPlJaJTMgkswTt8iV9HfEaj7GWFiP0M24URc76QWCOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});